name: 'JumpServer build and upload release assets'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: 'GITHUB_TOKEN for uploading releases to Github asserts.'
    required: true
    default: ''
  os:  # id of input
    description: 'os the running programs operating system target: one of darwin, freebsd, linux, and so on.'
    required: false
    default: ''
  arch:
    description: 'arch is the running programs architecture target: one of 386, amd64, arm, s390x, and so on.'
    required: false
    default: ''
  upload_url:
    description: 'the url for upload, default to release event url '
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.os }}
    - ${{ inputs.arch }}
    - ${{ inputs.upload_url }}
