name: 'JumpServer build and upload release assets'
description: 'Common action for create release and build'
inputs:
  os:  # id of input
    description: 'os the running programs operating system target: one of darwin, freebsd, linux, and so on.'
    required: false
    default: ''
  arch:
    description: 'arch is the running programs architecture target: one of 386, amd64, arm, s390x, and so on.'
    required: false
    default: ''
  upload_url:
    description: 'the url for upload, default to release event url '
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.os }}
    - ${{ inputs.arch }}
    - ${{ inputs.upload_url }}
